---
title: "Simulation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{simu}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = T,
  message = F, 
  warning = F
)

#https://pengsu517.github.io/robcovsel

library(tidyverse)
library(gridExtra)
library(grid)
library(plotly)
library(stargazer)
library(reshape2)
#library(mplot)
library(mfp)
options(show.error.locations = TRUE)
```


```{r, message = F, warning = F,echo=FALSE, fig.width=15, fig.height=15}
prostate_cancer = read.table("dat.txt")
data("bodyfat")
pairs(bodyfat[,-c(1,3,4)])

```


```{r}
y = bodyfat$brozek
x = as.matrix(bodyfat[,-(1:4)])

n = dim(x)[1]
p = dim(x)[2]

fit0 = regcell::Rlars(y,x)

ynew = y/fit0$sigmahat
xnew = as.matrix(robustHD::robStandardize(x))

fit_lasso = lasso_f(ynew,xnew)
fit_lasso

fit_rlars = rlarsf(ynew,xnew)
fit_rlars

fit_cell = cell_lasso_ddc_f(ynew,xnew)
fit_cell

fit_lasso_ddc = lasso_ddc_f(ynew, xnew)
fit_lasso_ddc
```


```{r}
library(tidyverse)
result1 = as.data.frame(t(as.data.frame(result)))
result1 = result1 %>% mutate(across(c(1,3), as.numeric))
```

```{r, fig.width=10, fig.height=10}
p1 = ggplot(data = result1)+
  geom_boxplot(aes(x = method, fill = method, y = loope)) 
p1

```










