---
title: 'Bodyfat'
author: "Peng"
format: 
  html: 
    ### IMPORTANT ###
    self-contained: true # Creates a single HTML file as output
    code-fold: show # Code folding; allows you to show/hide code chunks
    ### USEFUL ###
    code-tools: true # Includes a menu to show/hide all chunks
    ### OPTIONAL ###
    code-line-numbers: true # Line numbers in code chunks
    df-print: paged # Sets how dataframes are automatically printed
    theme: lux # Controls the font, colours, etc.
    table-of-contents: true # (Useful) Creates a table of contents!
    number-sections: true # (Optional) Puts numbers next to heading/subheadings
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F )
library(tidyverse)
library(usethis)
library(robustHD) #sparse LTS
library(cellWise)
library(corrplot)
library(mplot)
library(GGally)
library(srlmcell)
```

# Bodyfat
```{r analysis}
dat = bodyfat
dat$Id = NULL
x = dat[,-1]
#GGally::ggpairs(dat[,1:6]) + theme_bw()
```

## Outlier detection 

```{r fig.height=3, fig.width=15}
fit1 <- DDC(x)
p1 = cellMap(fit1$remX, fit1$stdResid, columnlabels = c(1,rep(" ",11),13), rowlabels = c(128,rep(" ",126),1), columnangle = 0,
        rowtitle = "Observations", columntitle = "Variables", sizetitles = 2,adjustrowlabels = 0.5, adjustcolumnlabels = 0.5)+
  coord_flip()+
   theme(axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        legend.title = element_text(size=14), #change legend title font size
        legend.text = element_text(size=12))
p1


```


## Variable selection

```{r}
{
  smrlarsrowf    = function(y, x){srlmcell::srlmm(y,x, tech = "row",   initial = "rlars")}
  smrlarscellf   = function(y, x){srlmcell::srlmm(y,x, tech = "cell",  initial = "rlars")}
  smddcrowf    = function(y, x){srlmcell::srlmm(y,x, tech = "row",   initial = "ddc")}
  smddccellf   = function(y, x){srlmcell::srlmm(y,x, tech = "cell",  initial = "ddc")}

  mtds = list(
    smrlarsrow    = smrlarsrowf,
    smrlarscell   = smrlarscellf,
    smddcrow    = smddcrowf,
    smddccell   = smddccellf
  )
}

```

```{r}
rst = list()
xtilderst = list()

for (mtd in 1:length(mtds)) {
  dat = bodyfat
  dat$Id = NULL
  y = dat$Bodyfat
  x = as.matrix(dat[,-1])
  timing  = system.time({fit = mtds[[mtd]](y,x)})["elapsed"]
  betahat = fit$betahat
  rst[[mtd]] = c(method = names(mtds)[mtd], betahat = betahat)
  xtilderst[[mtd]] = fit$flagger
  
}

rst = as.data.frame(t(as.data.frame(rst)))
rownames(rst) = NULL     

colnames(rst) = c("method", "beta0",names(dat)[-1]  )
```

```{r}
dat = bodyfat
dat$Id = NULL
y = dat$Bodyfat
x = dat[,-1]

#fit1 = shootings::sparseshooting(x,y)
#fit1$coef_ln

fit2 = srlmcell::Rlars(y,x)
fit2$betahat

#sss = c("shootings", fit1$coef_ln)
rlars = c("rlars", fit2$betahat)
rstnew = rbind(rst,  rlars)
rstnew %>% mutate(across(beta0:Wrist, as.numeric)) %>% knitr::kable(digits = 2)
```


```{r fig.height=3, fig.width=15 ,fig.cap="Flagged outliers by smrlarsrow"}
p2 = cellMap(x, 10*xtilderst[[1]], columnlabels = c(1,rep(" ",11),13), rowlabels = c(128,rep(" ",126),1), columnangle = 0,
        rowtitle = "Observations", columntitle = "Variables", sizetitles = 2,adjustrowlabels = 0.5, adjustcolumnlabels = 0.5)+
  coord_flip()+
   theme(axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        legend.title = element_text(size=14), #change legend title font size
        legend.text = element_text(size=12))
p2


```

```{r fig.height=3, fig.width=15 ,fig.cap="Flagged outliers by smrlarscell"}
p2 = cellMap(x, 10*xtilderst[[2]], columnlabels = c(1,rep(" ",11),13), rowlabels = c(128,rep(" ",126),1), columnangle = 0,
        rowtitle = "Observations", columntitle = "Variables", sizetitles = 2,adjustrowlabels = 0.5, adjustcolumnlabels = 0.5)+
  coord_flip()+
   theme(axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        legend.title = element_text(size=14), #change legend title font size
        legend.text = element_text(size=12))
p2


```


```{r fig.height=3, fig.width=15}
fit1 <- DDC(x)
p1 = cellMap(fit1$remX, fit1$stdResid, columnlabels = c(1,rep(" ",11),13), rowlabels = c(128,rep(" ",126),1), columnangle = 0,
        rowtitle = "Observations", columntitle = "Variables", sizetitles = 2,adjustrowlabels = 0.5, adjustcolumnlabels = 0.5)+
  coord_flip()+
   theme(axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        legend.title = element_text(size=14), #change legend title font size
        legend.text = element_text(size=12))
p1


```

