---
title: "realdata"
author: "pengsu"
date: "2023-03-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
dat = as.data.frame(t(read.csv("Normarrayexpressdata.txt.magetab", sep = "\t")))
datc = dat
colnames(datc) = datc[1,]
datcc = datc[-1,]

colnames(datcc)[1] = "id"
datcc$id = extract_numeric(rownames(datcc))

featuredat = read.csv("feature.txt", sep = "\t")
featuredat$id = extract_numeric(featuredat$Source.Name)

datall = merge(featuredat, datcc, by = "id")


y = datall$Characteristics..Total.Hip.T.score.
x = datall[,-(1:50)] %>% mutate(across(.fns = as.numeric))
logx = log(x)

datalog = cbind(y, logx)
# save(datalog, file = "datalog.RData")
```

```{r}
x = datalog[,-1]
y = datalog[,1]


# normalitytest = apply(x[,-c(21151, 41390)],2, function(xvec){shapiro.test(xvec)$p.value})

# xnormal = x[,which(normalitytest>0.01)]
xnormal = x

corh = apply(xnormal,2, function(xvec){robustHD::corHuber(xvec,y)})   
sort(abs(corh), decreasing = T)[1]

thresh = sort(abs(corh), decreasing = T)[1]
orders = order(abs(corh), decreasing = T)
abs(corh)[orders[1]]

xscreen = xnormal[,orders][,1:200]
corhs = apply(xscreen,2, function(xvec){robustHD::corHuber(xvec,y)}) 
sort(abs(corhs), decreasing = T)[1]

pairs(cbind(y,xscreen[,1:5]))

datascreen = cbind(y,xscreen)
# save(datascreen, file = "datascreen_corh.RData")
# save(datascreen, file = "datascreen.RData")

redundant = sort(sample(101:dim(xnormal)[2],100))

xscreen2 = xnormal[,orders][,c(1:100, redundant)]
corhs2 = apply(xscreen2,2, function(xvec){robustHD::corHuber(xvec,y)}) 
sort(abs(corhs2), decreasing = T)[1]
# barplot(abs(corhs2))
# pairs(cbind(y,xscreen[,1:5]))

datascreen2 = cbind(y,xscreen2)
save(datascreen2, file = "datascreen_corh2.RData")
```

```{r}
y = datascreen[,1]
x = as.matrix(datascreen[,2:101])

inTrain <- caret::createDataPartition(y, p = 0.7)[[1]]


ytrain = y[inTrain]
xtrain = x[inTrain,]

ytest = y[-inTrain]
xtest = x[-inTrain,]


fit0 = sregcell_std(ytrain,xtrain, penal = 1, softbeta = T, prob = 0.99, softzeta = 1, maxiter = 30)
# sort(fit0$betahat_post, decreasing = T)[1:50]
# fit0$betahat
# fit0$sigmahat
res = ytest - fit0$intercept_hat - xtest%*%fit0$betahat

fit1 = Rlars(ytrain,xtrain)
# sort(fit1$betahat, decreasing = T)[1:10]

res2 = ytest - fit1$betahat[1] - xtest%*%fit1$betahat[-1]

sd(res)
sd(res2)

hist(res)
hist(res2)
```



```{r}
mtds = list(
  sss = function(y, x){shootings::sparseshooting(x,y)$coef},
  rlars = function(y, x){regcell::Rlars(y, x)$betahat},
  mmlasso = function(y,x){mmlasso::mmlasso(x,y)$coef.MMLasso.ad},
  slts = function(y,x){robustHD::sparseLTS(x,y)$coefficients},

  # cell_scad = function(y,x, penal, penaldelta){
  #   fit = regcell::sregcell_std(y = y, x = x, softbeta = FALSE, lambda_zeta = 1, penal = 0.3, penaldelta = 0)
  #   return(c(fit$intercept_hat, fit$betahat))
  # },

  cell_lasso_post = function(y,x){
    fit = regcell::sregcell_std(y = y, x = x, softbeta = TRUE, lambda_zeta = 1, penal = 1, penaldelta =0)
    return(c(fit$intercept_hat_post, fit$betahat_post))
  },

  lasso  = function(y,x){
    return(regcell::slm2(y,x)$betahat)
  }

)
```


```{r}
betamat = matrix(NA, nrow = 100, ncol = length(mtds))
for(i in 1:length(mtds)){
  betamat[,i] = mtds[[i]](y,x)[-1]
}

colnames(betamat) = names(mtds)


betamat[which(rowSums(betamat!=0)==5),]
colSums(betamat!=0)
sum(rowSums(betamat[,-1]!=0)==5)
```




```{r fig.width=15, fig.height=2}
library(cellWise)
library(tidyverse)

# y = datascreen[,1]
# x = datascreen[,2:101]

x = bodyfat[,-(1:3)]

# x = datascreen[1:40,1:30]

fit1 <- cellWise::DDC(x)
p1 = cellWise::cellMap(fit1$remX, fit1$stdResid, columnlabels = c(1,rep(" ",dim(x)[2]-2),dim(x)[2]), rowlabels = c(1,rep(" ",dim(x)[1]-2),dim(x)[1]), columnangle = 0,
        rowtitle = "Observations", columntitle = "Genes", sizetitles = 2,adjustrowlabels = 0.5, adjustcolumnlabels = 0.5)+
   theme(axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        legend.title = element_text(size=14), #change legend title font size
        legend.text = element_text(size=12)) + coord_flip()
p1

#ggsave( "tbone.eps", plot = p1, width = 6, height = 5)

```


```{r}
corrplot::corrplot(cor(x), method = "shade", tl.col ="black",shade.col = NA, tl.srt = 45, order = "FPC")
```


```{r}
delta = ((x - fit1$Ximp)!=0)
mean(colMeans(delta))

max(colMeans(delta))
which.max(colMeans(delta))


max(rowMeans(delta))
which.max(rowMeans(delta))


boxplot(x)
```






```{r}


n = dim(x)[1]
num = length(mtds)

errormat = matrix(0, nrow = num, ncol = n)
for(mtd in 1:7){
  for(obs in 1:n){
    ytrain = y[-obs]
    xtrain = x[-obs,]
    ytest = y[obs]
    xtest = x[obs,]

    betahat = mtds[[mtd]](ytrain,xtrain)
    
    res = ytest - betahat[1] - sum(xtest*betahat[-1])
    errormat[mtd, obs] = res
  }
}



errordata = t(errormat)
colnames(errordata) = c("SSS", "RLars", "MM-Lasso", "SLTS", "CR-Scad", "CR-Lasso", "Lasso")
errordata = errordata[,c(6,7,3,2,4,1)]

apply(errordata,2, IQR)
apply(errordata,2, function(x){mean(sort(x^2, decreasing = F)[1:76])})
apply(errordata,2, function(x){mean(abs(x))})


save(errordata, file = "errordata.RData")

boxplot(errordata,cex.size = 0.5)
abline(h = 0, col = "red")


errordata  = errordata[,-5]
err1 = errordata %>% as.data.frame() %>% gather(key = "method", value = "error")

sum1 = err1 %>% group_by(method) %>% summarise(RMSPE = mean((error)^2), MAPE = mean(abs(error)))
```

```{r fig.width=6, fig.height=3}
p11 = ggplot(data = err1) + 
  geom_boxplot(aes(group = method, fill = method, y = error))+
  theme_bw()+
  labs(y = "LOO prediction error")+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        text= element_text(size=12), 
        legend.position = "right")
p11

#ggsave( "tbonerst.eps", plot = p11, width = 6, height = 3)
```




```{r}
betamat = matrix(nrow = 7, ncol = 101)
errormat = matrix(0, nrow = 7, ncol = 84)
for(mtd in 1:7){
  betahat = mtds[[mtd]](y,x)
  betamat[mtd,] = betahat
  res = y - betahat[1] - x%*%betahat[-1]
  errormat[mtd,] = res
}

rowSums(betamat!=0)
rownames(betamat) = rownames(errormat) = names(mtds)

boxplot(t(errormat))
apply(errormat, 1, sd)
```

```{r}

```



```{r}
library(robustbase)
data("tuna", package = "bayesm")
data("data_philips", package = "cellWise")
data("data_brands", package = "cellWise")
data("data_glass", package = "cellWise")
pairs(data_glass[,10:15])


data("bodyfat", package = "mfp")
data("TopGear", package = "robustHD")
data("coleman",package = "robustbase")
data("nci60", package = "robustHD")
data("aircraft", package="robustbase")
data("airmay", package="robustbase")
data("Animals2", package = "robustbase")
data(carrots, package = "robustbase")
data(salinity, package = "robustbase")
data("biomassTill", package="robustbase")
data(bushfire, package="robustbase")
data(vaso)
data(carrots, package="robustbase")
data(CrohnD, package="robustbase")
data(cushny, package="robustbase")
data(education, package="robustbase")
data(epilepsy, package="robustbase")
data(kootenay)
data(starsCYG, package = "robustbase")
data(stackloss)
glimpse(TopGear)

# x = log(TopGear[,c(7,9,10,11)])
x = cbind(log(TopGear[,c(7,9, 10, 12,14:17)]),TopGear$Acceleration)
y = TopGear[,13]

hist(TopGear$Acceleration)

dat = na.omit(cbind(y,x)) 
pairs(dat)
x = dat[,-1]
y = dat[,1]
xtrain = as.matrix(robustHD::robStandardize(x))
ytrain = robustHD::robStandardize(y)


# dat = as.data.frame(data_brands)
# xtrain = as.matrix(dat[,1:6])
# ytrain = dat[,7]
# ytrain = dat$y
# xtrain = as.matrix(robustHD::robStandardize(dat[,2:14]))
# xtrain = as.matrix(robustHD::robStandardize(bodyfat[,6:17]))
# ytrain = bodyfat$brozek-median(bodyfat$brozek)

```



```{r}
data(auto_mpg, package = "ascentTraining")
```




```{r}
library(tidyverse)
data("Boston", package = "MASS")
ytrain = log(Boston$medv)
Boston = Boston %>% mutate(loglstat = log(lstat), logdis = log(dis), logcrim = log(crim))
predictors = Boston[, c("loglstat", "rm", "logdis", "tax", "ptratio","nox", "age", "black", "logcrim")]
xtrain = as.matrix(predictors)

corrs = cor(predictors)
rownames(corrs) = colnames(corrs) = c("log(lstat)", "rm", "log(dis)", "tax", "ptratio","nox", "age", "black", "log(crim)")
corrsplot = corrplot::corrplot(corrs, method = "shade", tl.col ="black",shade.col = NA, tl.srt = 45, order = "FPC")
corrsplot

pairs(x)
```


```{r}
data("Diabetes",package = "heplots")
pairs(log(Diabetes[,1:5]))
```


```{r}
dat = read.table("slump_test.data.txt", sep = ",", header = T)

pairs(dat[,-1])

xtrain = as.matrix(dat[,2:8])
ytrain = dat[,9]
```



# Swiss nutrition data

```{r}
library(tidyverse)
dat = readxl::read_xlsx("swiss.xlsx")

dat[,12]
dim(dat)



labels = (1:39)*3 + 9
labels2 = (2:11)*3 + 9 # ingredient with water
dat1 = dat[,labels]
dat2 = dat[,labels2]

glimpse(dat2)

dat3 = dat2 %>% mutate(across(.fns = as.numeric))
# dat4 = dat3 %>% mutate_all(~replace(., is.na(.), 0))
dat5 = log(dat3)
pairs(log(dat5))

ytrain = dat5$`Cholesterol (mg)`
xtrain = dat5[,-5]
```












```{r}
fit1 = regcell::Rlars(ytrain,xtrain)
# sort(fit1$betahat, decreasing = T)[1:10]
fit1$betahat
fit1$sigmahat

# res2 = ytest - fit1$betahat[1] - xtest%*%fit1$betahat[-1]
# sd(res2)

```

```{r}
# ytrain = datascreen[,1]
# xtrain = as.matrix(datascreen[,-1])
fit2 = regcell::sregcell_std(ytrain, xtrain, penal = 1)
fit2$intercept_hat_post
fit2$betahat_post

sum(fit2$betahat_post!=0)
```


```{r}
fit3 = robustHD::sparseLTS(xtrain, ytrain)
fit3$coefficients
fit3$raw.scale
# res3 = ytest - fit3$coefficients[1] - xtest%*%fit3$coefficients[-1]
# sd(res3)
anyNA(x)
```

```{r}
fit4 = regcell::slm(ytrain,xtrain, type = "lasso")
fit4$betahat
# sort(fit4$betahat, decreasing = T)[1:10]
# fit4$sigmahat
# res4 = ytest - fit4$betahat[1] - xtest%*%fit4$betahat[-1]
# sd(res4)
```

```{r}
fit5 = shootings::sparseshooting(xtrain,ytrain)
fit5$coef
# res5 = ytest - fit5$coef[1] - xtest%*%fit5$coef[-1]
# sd(res5)
```




```{r}
lm(ytrain~xtrain)
```





```{r}
result1 = as.data.frame(result)
result1 = as.data.frame(t(result1))

tbl = result1 %>% spread(mtd, res)
tbl = tbl %>% mutate(across(.fns = as.numeric))

boxplot(tbl[,-(1:2)])

apply(tbl[,-(1:2)],2, function(x){mean(sort(x^2, decreasing = F)[1:75])})
apply(tbl[,-(1:2)],2, function(x){mean(abs(x))})
apply(tbl[,-(1:2)],2, IQR)
```



```{r fig.width=6, fig.height=4, echo=FALSE}
result11 = as.data.frame(t(as.data.frame(result)))
result2 = result11
result2$method = as.factor(result2$mtd)
levels(result2$method) = c("CR-Lasso", "Lasso", "MM-Lasso", "RLars", "SLTS", "SSS")
result2$method = factor(result2$method, levels = c("CR-Lasso", "SSS", "RLars", "MM-Lasso", "SLTS", "Lasso"))
result2$res = as.numeric(result2$res)
```


```{r}
library(tidyverse)
summ3 = result2 %>% group_by(method) %>% summarise(
  RMSPE = round(mean(res^2),2), 
  RTMSPE = round(mean(sort(res^2, decreasing = FALSE)[1:200]),2),
  MAPE = round(mean(abs(res)),2))
summ3
# xtable::xtable(t(summ3))

boxplot(res~method, data = result2,  ylab="LOO predictor error", xlab = "")
```



```{r fig.width=6, fig.height=3}
p1 = ggplot(data = result2)+
  geom_boxplot(aes(x = method, y = res),outlier.size = 0.2, lwd = 0.4)+
  facet_grid(.~., scales = "free", space = "free_x") +
  #scale_y_continuous(limits = quantile(result3$MAPE, c(0, 0.95)))+
  # ylim(0,6)+
  theme_bw()+
  theme(text= element_text(size=12), 
        #axis.text.x = element_blank(),
        legend.position = "right")
p1

# names = paste("plot_rmspe_sigma3_n200_p",unique(result3$p), ".eps", sep = "")
# ggsave("tbonerst1.eps", plot = p1, width = 6,height = 3)
```





```{r fig.width=6, fig.height=4, echo=FALSE}
result1 = as.data.frame(t(as.data.frame(result)))
result2 = result1 %>% mutate(across(c(1, 3:8), as.numeric), 
                             method = as.factor(mtd),
                             fp = 100-pr-tn,
                             fn = pr - tp,
                             BACC = (tp/pr + tn/(100-pr))/2,
                             F1 = 2*tp/(2*tp + fp + fn))
levels(result2$method) = c("CR-Lasso", "Lasso", "MM-Lasso", "RLars", "SLTS", "SSS")
levels(result2$method)
result2$method = factor(result2$method, levels = c("CR-Lasso", "SSS", "RLars", "MM-Lasso", "SLTS", "Lasso"))
```


```{r}
library(tidyverse)
summ2 = result2 %>% group_by(method, pr, sigma) %>% summarise(
  RMSPE = round(mean(rmspe),2), 
  MAPE = round(mean(mape),2),
  TP = round(mean(tp),2),
  TN = round(mean(tn),2),
  F1 = round(mean(F1),2))

summ3 = summ2 %>% filter(pr==10, sigma==0.5)
# xtable::xtable(t(summ3))
```



```{r fig.width=10, fig.height=10}
p1 = ggplot(data = result2)+
  geom_boxplot(aes(fill = method,x = method, y = rmspe),outlier.size = 0.2, lwd = 0.4)+
  facet_grid(sigma~pr, scales = "free", space = "free_x") +
  # scale_y_continuous(limits = quantile(result3$MAPE, c(0, 0.95)))+
  # ylim(0,6)+
  theme_bw()+
  theme(text= element_text(size=12), 
        #axis.text.x = element_blank(),
        legend.position = "right")
p1

# ggsave("tbonerst1.eps", plot = p1, width = 6,height = 3)
```
