---
title: "Simulation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{simu}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = T,
  message = F, 
  warning = F
)

#https://pengsu517.github.io/robcovsel

library(tidyverse)
library(gridExtra)
library(grid)
library(plotly)
library(stargazer)
library(reshape2)
options(show.error.locations = TRUE)
```


```{r, message = F, warning = F,echo=FALSE}
# load("result_simu_p20_newcode_0106.RData")
# assign('result111', get(load('result_simu_p200_new2.RData')))
```

```{r}
result_test = as.data.frame(t(as.data.frame(result)))
```



```{r}
result1low = as.data.frame(t(as.data.frame(result)))
names(result1low) = c("m", "n", "p", "pr", "e", "r", "gamma", "outtype", "df", "method", "seed",
                        "MSPE", "MAPE", "RTMSPE", "TP", "FP", "Time", paste("betahat", 1:10))
result1high = as.data.frame(t(as.data.frame(result)))
names(result1high) = c("m", "n", "p", "pr", "e", "r", "gamma", "outtype", "df", "method", "seed",
                        "MSPE", "MAPE", "RTMSPE", "TP", "FP", "Time", paste("betahat", 1:10))
result1lasso = as.data.frame(t(as.data.frame(result)))
names(result1lasso) = c("m", "n", "p", "pr", "e", "r", "gamma", "outtype", "df", "method", "seed",
                        "MSPE", "MAPE", "RTMSPE", "TP", "FP", "Time", paste("betahat", 1:10))
remove(result)
result1 = rbind(result1high, result1low, result1lasso)
result1 = result1high

save(result1, file = "data_all_in_one.RData")
```


```{r}
result2 = result1 %>% mutate(across(c(1:7,9, 11:21), as.numeric), 
                             across(5:11, as.factor), 
                             TN = p-pr-FP,
                             FN = pr - TP,
                             BACC = (TP/pr + TN/(p-pr))/2,
                             F1 = 2*TP/(2*TP + FP + FN),
                             MCC = (TP*TN-FP*FN)/sqrt((TP+FP)*(TN+FN)*pr*(p - pr)),
                             RMSPE = sqrt(MSPE))
# glimpse(result2)
# unique(result2$method)

levels(result2$e) = c("e = 0%", "e = 2%", "e = 5%")
levels(result2$df) = c("t(4)", "Normal")
result2$df = factor(result2$df, levels = c("Normal", "t(4)"))

levels(result2$gamma) = c(" ", "2", "4", "6", "8")
# levels(result2$r) = c("r = 0.25", "r = 0.5", "r = 0.75")
levels(result2$method) = c("CR-Lasso", "Lasso_old", "Lasso", "MM-Lasso", "RLars", "SLTS", "SSS")
result2$method = factor(result2$method, levels = c("CR-Lasso", "SSS", "RLars", "MM-Lasso", "SLTS", "Lasso", "Lasso_old"))
result2 = result2[complete.cases(result2),]

```

```{r}
#result2[which.max(result2$rtmspe),] 
result3 = result2 %>% filter((p==50)&(method!="Lasso_old"))

# result3 = result2 #%>% filter((n==100)&(pr==10)&(method %in% c("CR-Lasso", "Lasso", "MM-Lasso", "RLars")))

# result4 = result3 %>% filter((m==89)&(n==100)&(p==20)&(pr==10)&(e=="e = 2%")&(r=="0.5")&(gamma=="10")&(df=="t(3)"))
# result5 = result3[which.max(result3$RMSPE),]

# result5 = result3 %>% filter((method %in% c("cell_lasso_post3", "lasso", "mmlasso", "rlars")))
# unique(result3$p)
```


```{r fig.width=10, fig.height=7, echo=FALSE}

p1 = ggplot(data = result3)+
  geom_boxplot(aes(fill = method, x = gamma, y = RMSPE),outlier.size = 0.2, lwd = 0.4)+
  facet_grid(df~e, scales = "free", space = "free_x") +
  #scale_y_continuous(limits = quantile(result3$MAPE, c(0, 0.95)))+
  # ylim(0,6)+
  theme_bw()+
  labs(x = expression(gamma*": magnitude of outlyingness"))+
  theme(text= element_text(size=20), 
        #axis.text.x = element_blank(),
        legend.position = "bottom")
p1

names = paste("plot_rmspe_sigma3_n200_p",unique(result3$p), ".eps", sep = "")
ggsave(names, plot = p1, width = 10,height = 7)
```

```{r}

summary = result3 %>% group_by(n,p, pr,e,r,gamma, df, method,outtype) %>% summarise(
  TP = mean(TP, na.rm = T),
  FP = mean(FP, na.rm = T),
  TPR = mean(TP/pr, na.rm = T),
  FPR = mean(FP/(p-pr), na.rm = T),
  TNR = 1-FPR,
  BACC = mean(BACC),
  F1 = mean(F1),
  MCC = mean(MCC),
  Time = mean(Time))


summ =  result3 %>% group_by(method) %>% summarise(
  Time = mean(Time))
```


```{r fig.width=10, fig.height=7, echo=FALSE}
p2 = ggplot(data = summary, aes(x = gamma, y = TPR, group = method))+
  geom_point(aes(color = method))+
  geom_line(aes(linetype = method, color = method))+ 
  facet_grid(df~e, scales = "free", space = "free_x") +
  #scale_y_continuous(limits = c(0, 1))+
  ylim(0,1)+
  theme_bw()+
  labs(x = expression(gamma*": magnitude of outlyingness"))+
  theme(text= element_text(size=20), 
        #axis.text.x = element_blank(),
        legend.position = "bottom")
p2

names = paste("plot_tpr_sigma3_n200_p",unique(result3$p), ".eps", sep = "")
ggsave(names, plot = p2, width = 10,height = 7)
```



```{r fig.width=10, fig.height=7, echo=FALSE}

p2 = ggplot(data = summary, aes(x = gamma, y = FPR, group = method))+
  geom_point(aes(color = method))+
  geom_line(aes(linetype = method, color = method))+ 
  facet_grid(df~e, scales = "free", space = "free_x") +
  #scale_y_continuous(limits = c(0, 1))+
  ylim(0,1)+
  theme_bw()+
  labs(x = expression(gamma*": magnitude of outlyingness"))+
  theme(text= element_text(size=20), 
        #axis.text.x = element_blank(),
        legend.position = "bottom")
p2

names = paste("plot_fpr_sigma3_n200_p",unique(result3$p), ".eps", sep = "")
# ggsave(names, plot = p2, width = 10,height = 7)
```


```{r fig.width=10, fig.height=7, echo=FALSE}

p2 = ggplot(data = summary, aes(x = gamma, y = F1, group = method))+
  geom_point(aes(color = method))+
  geom_line(aes(linetype = method, color = method))+ 
  facet_grid(df~e, scales = "free", space = "free_x") +
  #scale_y_continuous(limits = c(0, 1))+
  ylim(0,1)+
  theme_bw()+
  labs(x = expression(gamma*": magnitude of outlyingness"), 
       y = expression(F[1]))+
  theme(text= element_text(size=20), 
        #axis.text.x = element_blank(),
        legend.position = "bottom")
p2

names = paste("plot_f1_sigma3_n200_p",unique(result3$p), ".eps", sep = "")
ggsave(names, plot = p2, width = 10,height = 7)
```





```{r}
result1 = as.data.frame(t(as.data.frame(result)))
names(result1) = c("m", "n", "p", "pr", "e", "sigma", "r", "gamma", "outtype", "df", "penal","penaldelta", "method", "seed",
                        "MSPE", "MAPE", "RTMSPE", "TP", "FP", "Time", paste("betahat", 1:10))
```


```{r}
result2 = result1 %>% mutate(across(c(1:8,10:12, 14:24), as.numeric), 
                             across(6:14, as.factor), 
                             TN = p-pr-FP,
                             FN = pr - TP,
                             BACC = (TP/pr + TN/(p-pr))/2,
                             F1 = 2*TP/(2*TP + FP + FN),
                             MCC = (TP*TN-FP*FN)/sqrt((TP+FP)*(TN+FN)*pr*(p - pr)),
                             RMSPE = sqrt(MSPE) )
# glimpse(result2)
# unique(result2$method)

# levels(result2$e) = c("e = 0%", "e = 2%", "e = 5%", "e = 10%")
# levels(result2$df) = c("t(3)", "t(5)", "Normal")
# levels(result2$gamma) = c(" ", "2", "4", "6", "8", "10")
# levels(result2$r) = c("r = 0.25", "r = 0.5", "r = 0.75")
# levels(result2$method)
# result2$method = factor(Method, levels = c("CS-Lasso", "CS-Scad", "Lasso", "MM-Lasso", "RLars", "SSS"))


result2 = result2[complete.cases(result2),]

```



```{r}
result3 = result2 %>% filter((sigma==3)&(p!=150))
# result3 = result2 %>% filter((n==100)&(pr==10)&(penal!=2)&(method=="cell_lasso_post"))

unique(result2$sigma)
```


```{r fig.width=10, fig.height=4, echo=FALSE}

# p1 = ggplot(data = result3)+
#   geom_boxplot(aes( fill = as.factor(penal), x = as.factor(p), y = F1),outlier.size = 0.2, lwd = 0.4)+
#   facet_grid(n~pr, scales = "free", space = "free_x") +
#   #scale_y_continuous(limits = quantile(result3$MAPE, c(0, 0.95)))+
#   # ylim(0,6)+
#   theme_bw()+
#   theme(text= element_text(size=12),
#         #axis.text.x = element_blank(),
#         legend.position = "right")
# p1


#ggsave("plots_rmspe_p20_pr10.eps", plot = p1, width = 10,height = 6)
```

```{r}

summary = result3 %>% group_by(n,p, pr,e,r,gamma, penal, penaldelta, df, method,outtype) %>% summarise(
  MAPE = mean(MAPE, na.rm = T),
  RMSPE = mean(RMSPE, na.rm = T),
  RTMSPE = mean(RTMSPE, na.rm = T),
  TPR = mean(TP/pr, na.rm = T),
  FPR = mean(FP/(p-pr), na.rm = T),
  TNR = 1-FPR,
  BACC = mean(BACC),
  MCC = mean(MCC),
  F1 = mean(F1),
  Time = mean(Time),
  size = n())%>%ungroup()

summary$pr = as.factor(summary$pr)
summary$n = as.factor(summary$n)
summary$penal = as.factor(summary$penal)

levels(summary$pr) = c("5 active predictors", "10 active predictors")
levels(summary$n) = c("n = 100", "n = 200")

```




```{r fig.width=6, fig.height=4, echo=FALSE}

summary$penal = as.numeric(as.character(summary$penal))
summary$`p: dimension` = as.factor(summary$p)
p1 = ggplot(data = summary)+
  geom_point(aes(color = `p: dimension`, x = penal, y = F1))+ 
  geom_line(aes( color = `p: dimension`, x = penal, y = F1),outlier.size = 0.2, lwd = 0.4)+
  facet_grid(n~pr, scales = "free", space = "free_x") +
  labs(fill = " ", x = expression("c: penalty parameter"), y = expression(F[1]))+ 
  #scale_y_continuous(limits = quantile(result3$MAPE, c(0, 0.95)))+
  ylim(0,1)+
  theme_bw()+
  theme(text= element_text(size=12), 
        #axis.text.x = element_blank(),
        legend.position = "right")
p1


#ggsave("plot_f1sigma3.eps", plot = p1, width = 6,height = 4)
```


```{r}
df <- expand.grid(X1 = 1:10, X2 = 1:10)
df$value <- df$X1 * df$X2

p1 <- ggplot(df, aes(X1, X2)) + geom_tile(aes(fill = value))
p2 <- p1 + geom_point(aes(size = value))

# Basic form
p1 + scale_fill_continuous(guide = guide_legend(title = "aaa"))
```












```{r}
summary2 = summary %>% select(n, p, pr, penal, BACC, MCC, F1)
summary3 = gather(summary2, key = "Measurement", value = "value", -c(penal, p, pr, n))
summary3 = summary3 %>% mutate(penal = as.numeric(as.character(penal)))
summary4 = summary3 %>% filter(p==50)

```


```{r fig.width=7, fig.height=3, echo=FALSE}
p23 = ggplot(data = summary4, aes(x = penal, y = value))+
  geom_point(aes(shape = Measurement ,color = Measurement))+
  geom_line(aes(linetype = Measurement, color = Measurement))+ 
  facet_grid(n~pr, scales = "free", space = "free_x") +
  #scale_y_continuous(limits = c(0, 1))+
  # ylim(0,1)+
  theme_bw()+
  labs(x = "c", y = "Value")+
  theme(text= element_text(size=12), 
        #axis.text.x = element_blank(),
        legend.position = "right")
p23
#ggsave("plot_bacc.eps", plot = p23, width = 7,height = 3)
```

```{r}
summary4 = summary %>% select(penal, RMSPE, MAPE, RTMSPE)
summary4 = gather(summary4, key = "Measurement", value = "value", -penal)
summary5 = summary4 %>% mutate(penal = as.numeric(as.character(penal)))
```

```{r fig.width=4, fig.height=3, echo=FALSE}
p24 = ggplot(data = summary5, aes(x = penal, y = value))+
  geom_point(aes(shape = Measurement ,color = Measurement))+
  geom_line(aes(linetype = Measurement, color = Measurement))+ 
  # facet_grid(.~pr, scales = "free", space = "free_x") +
  #scale_y_continuous(limits = c(0, 1))+
  ylim(0,2)+
  theme_bw()+
  labs(x = "c", y = "Value")+
  theme(text= element_text(size=12), 
        #axis.text.x = element_blank(),
        legend.position = "right")
#ggsave("plots_tpr_p20_pr10.eps", plot = p2, width = 10,height = 6)
```


```{r fig.width=8, fig.height=3}
p234 = grid.arrange(p23, p24, nrow = 1)
# robcovsel::grid_arrange_shared_legend(p23,p24, nrow = 1, ncol = 2, position = "right")
p234
```




```{r fig.width=10, fig.height=12, echo=FALSE}

p2 = ggplot(data = summary, aes(x = penal, y = TPR, group = method))+
  geom_point(aes(color = method))+
  geom_line(aes(linetype = method, color = method))+ 
  facet_grid(.~pr, scales = "free", space = "free_x") +
  #scale_y_continuous(limits = c(0, 1))+
  ylim(0,1)+
  theme_bw()+
  labs(x = expression(gamma*": magnitude of outlyingness"))+
  theme(text= element_text(size=12), 
        #axis.text.x = element_blank(),
        legend.position = "right")
p2


#ggsave("plots_fpr_p20_pr10.eps", plot = p2, width = 10,height = 6)
```

```{r}
result1 = as.data.frame(t(as.data.frame(result)))
names(result1) = c("m", "n", "p", "pr", "e", "r", "gamma", "outtype", "df", 
                   "eta1", "eta2", "seed", "MSPE", "MAPE", "RTMSPE", 1:5, "Time")

result1 = result1 %>% mutate(across(c(m:gamma, df:Time), as.numeric))
# glimpse(result1)

result1$df = factor(result1$df, labels = c("Normal", "t(3)", "t(5)"))
result1$df = factor(result1$df, levels = c("t(3)", "t(5)", "Normal"))

result1$eta2 = factor(result1$eta2)

result1$eta1 = factor(result1$eta1)

max(result1$MSPE)
```


```{r fig.width=10, fig.height=4, echo=FALSE}
result2 = result1 %>% filter(eta1 == 100)
p1 = ggplot(data = result2)+
  geom_boxplot(aes(x = eta2, fill = eta2, y = MSPE),outlier.size = 0.2, lwd = 0.4)+
  #ylim(0,10)+
  facet_grid(.~df, scales = "free", space = "free_x")
p1


#ggsave("plots_eta100.eps", plot = p1, width = 10,height = 4)
```




