# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

threshold_vec <- function(xvec, lambdavec, soft = TRUE) {
    .Call(`_regcell_threshold_vec`, xvec, lambdavec, soft)
}

threshold_mat <- function(xmat, lambdamat, soft = TRUE) {
    .Call(`_regcell_threshold_mat`, xmat, lambdamat, soft)
}

threshold_svd <- function(x, lambdavec, soft = TRUE) {
    .Call(`_regcell_threshold_svd`, x, lambdavec, soft)
}

rob_pca <- function(x, xc, delta, lambda, maxiter = 1000L) {
    .Call(`_regcell_rob_pca`, x, xc, delta, lambda, maxiter)
}

reg_beta <- function(y, x, betahat, intercept, alambdavec_beta, softbeta = TRUE, maxiterbeta = 2) {
    .Call(`_regcell_reg_beta`, y, x, betahat, intercept, alambdavec_beta, softbeta, maxiterbeta)
}

reg_delta <- function(y, x, betahat, deltahat, alambdamat_delta, alpha, softdelta = TRUE, maxiterdelta = 2) {
    .Call(`_regcell_reg_delta`, y, x, betahat, deltahat, alambdamat_delta, alpha, softdelta, maxiterdelta)
}

reg_beta_delta <- function(y, x, betahat, intercept, deltahat, cellweight, lambda_beta, softbeta, lambda_delta, softdelta, alpha, maxiter = 20) {
    .Call(`_regcell_reg_beta_delta`, y, x, betahat, intercept, deltahat, cellweight, lambda_beta, softbeta, lambda_delta, softdelta, alpha, maxiter)
}

