# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

soft_threshold_beta <- function(betahat, alambda_beta) {
    .Call(`_regcell_soft_threshold_beta`, betahat, alambda_beta)
}

soft_threshold_delta <- function(deltahat, alambda_delta) {
    .Call(`_regcell_soft_threshold_delta`, deltahat, alambda_delta)
}

reg_beta <- function(y, x, betahat, intercept, lambda_beta, adabeta, maxiter = 30) {
    .Call(`_regcell_reg_beta`, y, x, betahat, intercept, lambda_beta, adabeta, maxiter)
}

reg_delta <- function(y, x, betahat, deltahat, lambda_delta, cellweight, alpha, maxiter = 30) {
    .Call(`_regcell_reg_delta`, y, x, betahat, deltahat, lambda_delta, cellweight, alpha, maxiter)
}

reg_beta_delta <- function(y, x, betahat, intercept, deltahat, cellweight, lambda_beta, adabeta, lambda_delta, alpha, maxiter = 30) {
    .Call(`_regcell_reg_beta_delta`, y, x, betahat, intercept, deltahat, cellweight, lambda_beta, adabeta, lambda_delta, alpha, maxiter)
}

lambdamax_beta <- function(y, x, betahat, intercept, adabeta, lambdamax = 1) {
    .Call(`_regcell_lambdamax_beta`, y, x, betahat, intercept, adabeta, lambdamax)
}

